# Generated by Django 4.2.18 on 2025-01-30 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="record", name="province",),
    ]
